spring:
  profiles:
    active: ${APP_ENV:local}
  data:
  cache:
    jcache:
      config: classpath:ehcache.xml
info:
  app:
    home-page: ${APP_BASE_URL:http://localhost:8080}/swagger-ui.html
    git-repo: https://github.com/mrazjava/booklink
    description: "@project.description@"
management:
  info:
    git:
      mode: full
  health:
      enabled: false
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,loggers
booklink:
  security:
    cors-allow-origins: ${CORS_ALLOW_ORIGINS:}
